Grating fix
bonvision/BonVision pull request #8
Opened 2021-02-01 15:53 UTC by znamensk

Proposed fix for issue #7.

`Grating.vert` now simply returns `vt` as `texCoord`. `Grating.frag` has separate `frequency_x` and `frequency_y` uniforms and grating orientation is set by adjusting them in the workflow.

2021-03-06 20:54 UTC, glopesdev commented
Finally got a chance to review this, overall it looks great. I have only a couple of optimizations such as implementing `frequency` using a `vec2` uniform instead of two separate uniforms. This also allows refactoring the `SetFrequency` group to use only one `Zip` operator rather than two, similar to the original implementation.

However, I noticed one downside of this approach. Using this solution, if you draw a circular grating and continuously animate the `Angle` property, the gratings will not rotate around the center of the gratings, but rather seem to show an offset pivot. I'm still trying to wrap my head around why this happens and how to fix it.

I think this was the main reason why I switched to using a texCoord rotation, to avoid having to think about grating orientation in the fragment shader. Will update when I make progress.

2021-03-07 14:57 UTC, znamensk commented
Hmm... Good point. In the amended version gratings currently rotate around (0,0) in UV coordinates. I need to test it but I think simply subtracting 0.5 from `texCoord` along both dimensions in the vertex shader should make them rotate around the centre?

2021-03-07 21:17 UTC, glopesdev requested changes
Centring the texture coordinates does the trick, so in that case below are the only changes I would do before merging.


Replace the two frequency uniforms with a `vec2` field:
https://github.com/bonvision/BonVision/blob/23b933c90ef995a6d40003e5b8208effece815ab/BonVision/Shaders/Gratings.frag#L6-L7

```glsl
uniform vec2 frequency;
```

The value calculation then has to be updated to take into account centring as you suggested:
https://github.com/bonvision/BonVision/blob/23b933c90ef995a6d40003e5b8208effece815ab/BonVision/Shaders/Gratings.frag#L17

```glsl
  float value = (texCoord.x - 0.5) * frequency.x + (texCoord.y - 0.5) * frequency.y + phase;
```

Finally, having a single uniform allows simplifying the `SetFrequency` group to use only a single `Zip` operator, like so:
![image](https://user-images.githubusercontent.com/5315880/110255200-61535e00-7f8a-11eb-8f27-5be4e78f64f0.png)

Where the `ExpressionTransform` operator reads:
```c#
new(
single(Item1 * Math.Cos(Item4) * Item3) as Fx,
single(Item2 * Math.Sin(Item4) * Item3) as Fy)
```

2021-03-08 20:35 UTC, glopesdev commented
@znamensk I was curious to try the suggested edits feature of GitHub. Can you check if your branch is set to allow edits from maintainers? If it is, I should be able to suggest the changes myself by directly adding commits to the forked branch.

On the GitHub doc pages there is more info about [allowing changes to a pull request branch created from a fork]( https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

2021-03-12 14:01 UTC, znamensk commented
I somehow don't see the **Allow edits from maintainers** checkbox from my end... From what I understood from Github docs, it should be on this pull request - I made the pull request directly to this upstream repo.

2021-03-15 12:31 UTC, glopesdev commented
Strange... in that case, maybe I can merge the pull request as it is and then take it from there, if that works for you?

2021-03-19 21:07 UTC, znamensk commented
Sure, of course.

2021-03-25 01:13 UTC, merged